# Generated by Django 5.0.6 on 2024-07-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReco',
        ),
    ]
