# Generated by Django 5.0.6 on 2024-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0002_delete_dailyreco'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
